devonfw/devon4j

boms/bom/pom.xml, modules/security/pom.xml, pom.xml
#8: fixed build to work with Java8 and Java9-11
#9: fixed dependencies so security also works with Java8 and Java9-11
=> #8 and #9: Support for Java8-11

modules/service/src/main/java/com/devonfw/module/service/common/impl/discovery/ServiceDiscovererImplConfig.java, templates/server/src/main/resources/archetype-resources/core/src/main/resources/application.properties, templates/server/src/main/resources/archetype-resources/core/src/main/resources/config/application.properties
=> Fixed bug with context-path after upgrade to spring-boot 2.0 #6

boms/bom/pom.xml, templates/server/src/main/resources/archetype-resources/core/pom.xml, templates/server/src/main/resources/archetype-resources/server/src/main/resources/logback.xml
=> #7: use json logging for non-dev usage by default

modules/cxf-client-rest/src/main/java/com/devonfw/module/cxf/common/impl/client/rest/RestServiceExceptionMapper.java
PR for https://github.com/devonfw/devon4j/issues/45
=> Fixed NPE for uuid instance

pom.xml
simply add profile to `.m2/settings.xml` with property `gpg.keyname` to configure your key
=> externalize PGP key

templates/server/src/main/resources/archetype-resources/core/src/test/java/__packageInPathFormat__/general/common/base/test/ApplicationComponentTest.java
Resolves #60 as written in the issue itself.
=> #60 fix - mock web application context rather then remove it on component tests

templates/server/src/main/resources/archetype-resources/core/src/main/resources/application.properties
…which is enabled in spring-boot by default
See issue #65
=> #65: disabled open-session-in-view antipattern

modules/json/src/main/java/com/devonfw/module/json/common/base/type/PageableJsonDeserializer.java
Issue is fixed and tested .need to send given below data from Postman ,
{
"email": null,
"bookingToken": null,
"pageable":
{ "pageSize": 5, "pageNumber": 2, "sort": [] }
}
Issue Link- https://github.com/devonfw/devon4j/issues/87
=> NPE bug in paging JSON mapping

pom.xml, templates/server/src/main/resources/archetype-resources/pom.xml
PR for issue # https://github.com/devonfw/devon4j/issues/93
=> Update to spring boot 2.0.9 for bugfix release

boms/bom/pom.xml, modules/beanmapping/pom.xml, modules/beanmapping/src/main/java/com/devonfw/module/beanmapping/common/impl/dozer/BeanMapperImplDozer.java, modules/beanmapping/src/main/java/com/devonfw/module/beanmapping/common/impl/dozer/IdentityConverter.java, modules/beanmapping/src/test/java/com/devonfw/module/beanmapping/common/impl/dozer/BeanMapperImplDozerTest.java, modules/beanmapping/src/test/resources/config/app/common/dozer-mapping.xml, modules/jpa-dao/src/test/java/com/devonfw/example/general/common/api/config/BeansDozerConfig.java, modules/jpa-dao/src/test/resources/config/app/common/dozer-mapping.xml, templates/server/src/main/resources/archetype-resources/core/pom.xml, templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/config/BeansDozerConfig.java, templates/server/src/main/resources/archetype-resources/core/src/main/resources/config/app/common/dozer-mapping.xml
Dozer Upgraded with the latest version 6.4.1 (Issue:- https://github.com/devonfw/devon4j/issues/72)
=> Dozer Mapper Upgrade

documentation/devon4j-doc.asciidoc, documentation/guide-jdk.asciidoc
=> #99: added JDK guide

boms/bom/pom.xml
=> Updated mmm-util libraries to 8.7.0

modules/json/src/main/java/com/devonfw/module/json/common/base/ObjectMapperFactory.java, modules/json/src/main/java/com/devonfw/module/json/common/base/type/JsonPage.java, pom.xml, templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/config/ApplicationObjectMapperFactory.java, templates/server/src/main/resources/archetype-resources/pom.xml
Fix for issue 
https://github.com/devonfw/devon4j/issues/12
https://github.com/devonfw/devon4j/issues/106
Fix does not include IdRef
=> Spring boot upgrade and JSON mapping issue

modules/json/src/main/java/com/devonfw/module/json/common/base/ObjectMapperFactory.java, modules/json/src/test/java/com/devonfw/module/json/common/base/type/ObjectMapperFactoryTest.java, pom.xml, templates/server/src/main/resources/archetype-resources/pom.xml
#118: avoid redundant spring.boot.version
#112: renamed test to ObjectMapperFactoryTest
=> #97: updated owasp dependency-check and prevent breaking site build

pom.xml
=> #108: fixed javadoc for JDK11

modules/cxf-client-rest/src/main/java/com/devonfw/module/cxf/common/impl/client/rest/RestServiceExceptionMapper.java, modules/json/src/test/java/com/devonfw/module/json/common/base/type/TestObjectMapperFactory.java, modules/rest/src/main/java/com/devonfw/module/rest/service/impl/RestServiceExceptionFacade.java, modules/test/src/main/java/com/devonfw/module/test/common/api/category/CategoryComponentTest.java, modules/test/src/main/java/com/devonfw/module/test/common/api/category/CategoryModuleTest.java, modules/test/src/main/java/com/devonfw/module/test/common/api/category/CategorySubsystemTest.java, modules/test/src/main/java/com/devonfw/module/test/common/api/category/CategorySystemTest.java, templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/config/ApplicationObjectMapperFactory.java, templates/server/src/main/resources/archetype-resources/core/src/main/resources/config/application.properties
=> #141: fixed wiki/documentation links

documentation/devon4j-doc.asciidoc
=> #124: fixed layer TOC

templates/server/src/main/resources/archetype-resources/server/pom.xml
=> #133: removed duplicated property java.version

boms/minimal/pom.xml, modules/test-jpa/src/main/java/com/devonfw/module/test/common/base/ComponentDbTest.java
Fix issue
https://github.com/devonfw/devon4j/issues/149
https://github.com/devonfw/devon4j/issues/148
=> junit update devonj_test_jpa

boms/minimal/pom.xml, documentation/guide-jpa.asciidoc, templates/server/src/main/resources/archetype-resources/core/pom.xml, templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/dataaccess/impl/JpaConfig.java, templates/server/src/main/resources/archetype-resources/core/src/test/java/__packageInPathFormat__/general/common/impl/config/TestDbConfig.java, templates/server/src/main/resources/archetype-resources/core/src/test/java/__packageInPathFormat__/general/service/base/test/RestServiceTest.java
Fix for issue
https://github.com/devonfw/devon4j/issues/150
=> Improve JpaInitializer for test and prod

boms/bom/pom.xml, pom.xml, templates/server/src/main/resources/archetype-resources/pom.xml
update to spring-boot `2.1.9.RELEASE` for issue #96
=> #96: update to spring-boot 2.1.9

boms/bom/pom.xml, boms/minimal/pom.xml
=> #183: fixed BOMs so devon4j and archetype can be used again

boms/bom/pom.xml
see https://github.com/devonfw/devon4j/issues/204
=> Set slf4j-api to 1.7.28 and include jcl-over-slf4j in dependencymgmt

templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/service/impl/config/WebSecurityBeansConfig.java
=> #211: fixed spring config for access-control

documentation/guide-logging.asciidoc
see https://github.com/devonfw/devon4j/issues/39
=> Document logging of custom field in json

documentation/guide-batch-layer.asciidoc, documentation/guide-logging.asciidoc
https://github.com/devonfw/devon4j/issues/90
=> Documentation for authentication of batches

CHANGELOG.asciidoc
depend on PR https://github.com/devonfw/ide/pull/362
=> added change log

boms/minimal/pom.xml, modules/kafka/src/test/java/com/devonfw/example/module/MessageTestSender.java, starters/pom.xml, starters/starter-kafka-receiver/pom.xml, starters/starter-kafka-receiver/src/main/resources/META-INF/spring.factories, starters/starter-kafka-sender/pom.xml, starters/starter-kafka-sender/src/main/resources/META-INF/spring.factories, starters/starter-kafka-sender/src/test/java/com/defonfw/starters/kafka/sender/EmbeddedKafkaConsumerProperties.java, starters/starter-kafka-sender/src/test/java/com/defonfw/starters/kafka/sender/TestApplication.java, starters/starter-kafka-sender/src/test/java/com/defonfw/starters/kafka/sender/TestKafkaSenderSetup.java
@ravicm2 I created two starters for kafka.
Please use them in the example app you are currently working on.
=> Provide starters for kafka

modules/kafka/src/main/java/com/devonfw/module/kafka/common/messaging/api/config/MessageSenderConfig.java, modules/kafka/src/main/java/com/devonfw/module/kafka/common/messaging/impl/MessageSenderImpl.java, modules/kafka/src/main/java/com/devonfw/module/kafka/common/messaging/logging/impl/ProducerLoggingListener.java, modules/kafka/src/main/java/com/devonfw/module/kafka/common/messaging/retry/api/config/MessageDefaultRetryConfig.java, modules/kafka/src/main/java/com/devonfw/module/kafka/common/messaging/retry/impl/DefaultRetryPolicy.java, modules/kafka/src/main/java/com/devonfw/module/kafka/common/messaging/retry/impl/MessageRetryTemplate.java, modules/kafka/src/test/java/com/devonfw/example/base/config/TestMessageSenderConfig.java, modules/kafka/src/test/java/com/devonfw/example/module/MessageTestSender.java
Made some improvements to the generics in devon-kafka
=> Rework generics in devon-kafka

templates/server/pom.xml, templates/server/src/main/resources/archetype-resources/__batch__/pom.xml, templates/server/src/main/resources/archetype-resources/core/pom.xml
see https://github.com/devonfw/devon4j/issues/266
=> Do not enable resource filtering by default

documentation/pom.xml
=> #253: update docgen for consistent maven-parent config

documentation/guide-service-versioning.asciidoc
Resolve remaining warnings from issue #252.
=> #252: prevent docgen warnings

documentation/guide-security.asciidoc, documentation/guide-xml.asciidoc
=> #277: updated security guide to recent OWASP top 10

.travis.yml
=> #289: update travis dist to bionic

pom.xml
=> #287: update spring-boot to 2.3.3

pom.xml
=> #288: update jackson to 2.11.2

documentation/_Sidebar.asciidoc, documentation/devon4j.asciidoc, documentation/guide-structure.asciidoc
Improved documentation as suggested in #295
=> #295: added guide for project/app structure

pom.xml
=> #293: update parent POM to get latest OWASP dependency plugin

modules/service/src/main/java/com/devonfw/module/service/common/base/client/async/AbstractAsyncServiceClient.java
Fix for NPE in error handling identified in bug issue #324.
=> #324: fix of NPE in error handling

documentation/devon4j.asciidoc
=> add missing guide-access-control-schema

documentation/tutorial-newapp.asciidoc
=> #345: fix to avoid outdated devon4j version without maintenance

documentation/guide-dataaccess-layer.asciidoc, documentation/guide-jms.asciidoc, documentation/guide-logic-layer.asciidoc
This PR changes docs according to #354
=> Change documentation for JMS sender layer 

.github/workflows/sonar.yml, sonar-project.properties
=> 294: config for sonarcloud via GH action

documentation/guide-service-layer.asciidoc
Addresses issue #341 by improving service-layer documentation.
=> #341: updated service-layer doc

pom.xml
implements #370 by updating dependency versions.
=> #370: dependency updates

CHANGELOG.asciidoc, boms/minimal/pom.xml, modules/pom.xml, starters/pom.xml
=> #373: added missing CORS modules

documentation/tutorial-newapp.asciidoc
=> #358: changed badge to JavaDoc to fix build on windows.

.github/workflows/build-pr.yml, templates/server/src/main/resources/archetype-resources/core/src/test/java/__packageInPathFormat__/general/common/base/ApplicationTest.java
=> #323: added spring integration test

documentation/guide-client-layer.asciidoc
=> #344: updated client doc

templates/server/src/main/resources/archetype-resources/core/pom.xml
Redone changes of #359 without reformatting velocity macros.
=> #359: redo changes (remove BOM, replace Tabs, fix indent)

documentation/pom.xml
update docgen to 2021.04.001 with several bugfixes.
=> update docgen to 2021.04.001

templates/server/src/main/resources/archetype-resources/pom.xml
=> #389: fixed by flattening POMs in archetype

templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/security/BaseUserDetailsService.java, templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/service/impl/config/BaseWebSecurityConfig.java
=> #400: no ROLE_ prefix using authorities

CHANGELOG.asciidoc, documentation/guide-jwt.asciidoc, modules/security-jwt/src/main/java/com/devonfw/module/security/jwt/common/api/JwtManager.java, modules/security-jwt/src/main/java/com/devonfw/module/security/jwt/common/base/JwtConstants.java, modules/security-jwt/src/main/java/com/devonfw/module/security/jwt/common/impl/JwtAuthenticatorImpl.java, modules/security-jwt/src/main/java/com/devonfw/module/security/jwt/common/impl/JwtConfigProperties.java, modules/security-jwt/src/main/java/com/devonfw/module/security/jwt/common/impl/JwtCreatorImpl.java, modules/security/src/main/java/com/devonfw/module/security/common/api/accesscontrol/AccessControlProvider.java, starters/starter-security-jwt/src/test/java/com/devonfw/module/security/jwt/common/api/JwtAuthenticatorTest.java, starters/starter-security-jwt/src/test/java/com/devonfw/module/security/jwt/common/api/JwtComponentTest.java, starters/starter-security-jwt/src/test/java/com/devonfw/module/security/jwt/common/api/JwtCreatorTest.java, starters/starter-security-jwt/src/test/java/com/devonfw/module/security/jwt/common/api/JwtManagerTest.java, starters/starter-security-jwt/src/test/java/com/devonfw/module/security/jwt/common/base/kafka/JwtTokenValidationAspectTest.java
=> #397: support JWT microprofile

documentation/guide-jpa-idref.asciidoc, documentation/guide-jpa.asciidoc, modules/basic/src/main/java/com/devonfw/module/basic/common/api/reference/IdRef.java, modules/jpa-basic/src/main/java/com/devonfw/module/jpa/dataaccess/api/JpaInitializer.java
=> #393: improved/fixed idref doc

documentation/devon4j.asciidoc
Rename Chapter
devonfw for Java (devon4j) -> Java
=> devonfw for Java (devon4j) -> Java

documentation/devon4j.asciidoc
=> Revert "Rename titel"

documentation/_Sidebar.asciidoc, documentation/architecture.asciidoc, documentation/devon4j.asciidoc, documentation/quarkus/guide-cors-support.asciidoc, documentation/quarkus/guide-logging.asciidoc
Added already existing quarkus guides in documentation/quarkus subfolder. Restructured documentation for alignment in devonfw guide https://github.com/devonfw/devon4j/issues/420.
This included this PR  https://github.com/devonfw/devonfw-guide/pull/144
=> Added quarkus guides and restructured documentation

documentation/devon4j.asciidoc
Belongs to https://github.com/devonfw/devon4j/issues/420
=> Adapt devon4j.asciidoc 

documentation/devon4j.asciidoc, documentation/guide-security.asciidoc
moved universal sections to general for issue #420
=> #420: moved universal sections to general

documentation/devon4j.asciidoc, documentation/guide-database-migration.asciidoc, documentation/guide-flyway.asciidoc, documentation/guide-liquibase.asciidoc
more for issue #420:
* moved SQL and db migration to general
* generalized db migration for spring/quarkus and splitted between flyway and liquibase
=> #420: more generalization

documentation/devon4j.asciidoc, documentation/guide-client-layer.asciidoc, documentation/guide-dependency-injection.asciidoc, documentation/guide-jmx.asciidoc, documentation/guide-json.asciidoc, documentation/guide-jwt.asciidoc, documentation/guide-liquibase.asciidoc, documentation/guide-log-monitoring.asciidoc, documentation/guide-logging.asciidoc, documentation/guide-monitoring.asciidoc, documentation/guide-transactions.asciidoc, documentation/quarkus.asciidoc, documentation/spring.asciidoc, documentation/spring/guide-jwt-spring.asciidoc
improvements for issue #420:
* rewritten monitoring stuff
* rewritten logging stuff
* extracted log-monitoring and JMX
* generalized tx guide
=> #420: generalization and consolidation

documentation/devon4j.asciidoc, documentation/quarkus.asciidoc
Added the spring-to-Quarkus migration guide to the outline
=> added link to migration guide

documentation/quarkus/guide-quarkus-configuration.asciidoc
Closes https://github.com/devonfw/devon4j/issues/475
=> Describe how to deal with secrets in Quarkus

documentation/guide-jpa-query.asciidoc, documentation/guide-repository.asciidoc
Closes https://github.com/devonfw/devon4j/issues/478
* Added section for native queries
* Added section that describes how to avoid the fragment approach when implementing repositories
=> Refactoring query and repository guide

.github/workflows/devonfw-spellcheck.yml
Updated the .yml file to re use the workflow from the central .github repository.
=> Updated devonfw-spellcheck.yml

.github/workflows/build-pr.yml, .github/workflows/build.yml
=> #503: reduce carbon footprint

templates/server/src/main/resources/archetype-resources/api/src/test/java/__packageInPathFormat__/ToTest.java
=> Changed toTest to support SortedSet

pom.xml
easy one for #585: update apache cxf to 3.5.5
=> #585: update apache cxf to 3.5.5

boms/bom/pom.xml, modules/kafka/pom.xml, modules/pom.xml, pom.xml, starters/pom.xml
part of story #585: update snakeyaml from 1.30 to 1.33
=> #585: update snakeyaml from 1.30 to 1.33
