boms/bom/pom.xml
simple fix to upgrade to `2.9.6` (that comes from spring BOM).
=> #28: fixed jackson versioning

modules/basic/src/main/java/com/devonfw/module/basic/common/api/entity/RevisionedPersistenceEntity.java, modules/jpa-dao/src/test/java/com/devonfw/example/general/dataaccess/api/TestApplicationPersistenceEntity.java, modules/jpa-dao/src/test/java/com/devonfw/module/jpa/dataaccess/base/AbstractPersistenceEntity.java, modules/jpa-envers/src/main/java/com/devonfw/module/jpa/dataaccess/api/GenericRevisionedDao.java, modules/jpa-envers/src/main/java/com/devonfw/module/jpa/dataaccess/api/RevisionedDao.java, modules/jpa-envers/src/main/java/com/devonfw/module/jpa/dataaccess/api/RevisionedMasterDataDao.java, modules/jpa-envers/src/main/java/com/devonfw/module/jpa/dataaccess/base/AbstractGenericRevisionedDao.java, modules/jpa-envers/src/main/java/com/devonfw/module/jpa/dataaccess/base/AbstractRevisionedDao.java, modules/jpa-spring-data/src/main/java/com/devonfw/module/jpa/dataaccess/api/data/GenericRevisionedRepository.java, starters/starter-spring-data-jpa/src/test/java/com/devonfw/example/general/dataaccess/api/TestApplicationPersistenceEntity.java
I did a refactoring during #18 and moved the `PersistenceEntity` interface from `jpa-basic` to `basic`.
However, I accidentally forgot that for `RevisionedPersistenceEntity` what is fixed with this PR before we finally complete our first release. This allows to reference the interface (e.g. in `api` module) without the full `jpa` dependencies.
=> moved RevisionedPersistenceEntity to devon4j-basic

boms/bom/pom.xml, modules/basic/pom.xml, modules/batch/src/main/java/com/devonfw/module/batch/common/base/SpringBootBatchCommandLine.java, modules/jpa-basic/pom.xml, pom.xml, templates/server/src/main/resources/archetype-resources/core/pom.xml, templates/server/src/main/resources/archetype-resources/pom.xml
This PR is for issue https://github.com/devonfw/devon4j/issues/12
=> Spring boot upgrade 2.1.2.RELEASE

boms/minimal/pom.xml
isolated final fix for #77 that @AbhayChandel found and fixed in #113
=> #77: consistently removed devon4j-configuration also from BOM

modules/basic/src/main/java/com/devonfw/module/basic/common/api/RevisionMetadata.java, modules/basic/src/main/java/com/devonfw/module/basic/common/api/RevisionMetadataType.java, modules/jpa-basic/src/main/java/com/devonfw/module/jpa/dataaccess/api/JpaHelper.java, modules/jpa-basic/src/main/java/com/devonfw/module/jpa/dataaccess/api/RevisionMetadata.java, modules/jpa-basic/src/main/java/com/devonfw/module/jpa/dataaccess/api/RevisionMetadataType.java, modules/jpa-basic/src/main/java/com/devonfw/module/jpa/dataaccess/impl/LazyRevisionMetadata.java, modules/jpa-envers/src/main/java/com/devonfw/module/jpa/dataaccess/api/GenericRevisionedDao.java, modules/jpa-envers/src/main/java/com/devonfw/module/jpa/dataaccess/base/AbstractGenericRevisionedDao.java, modules/jpa-spring-data/src/main/java/com/devonfw/module/jpa/dataaccess/api/data/GenericRevisionedRepository.java, modules/jpa-spring-data/src/main/java/com/devonfw/module/jpa/dataaccess/impl/data/GenericRevisionedRepositoryImpl.java
Fix for Issue : - #47 .
This is new PR created against PR https://github.com/devonfw/devon4j/pull/134
=> Revision meta data

templates/server/src/main/resources/archetype-resources/core/src/main/resources/config/application.properties
In every training, I am teaching to enable SQL debugging in hibernate during development as best practice.
Hence, we should have this preconfigured for dev (`config/application.properties`) in our archetype.
=> show SQL from hibernate during development for debugging

modules/json/src/main/java/com/devonfw/module/json/common/base/ObjectMapperFactory.java, modules/json/src/test/java/com/devonfw/module/json/common/base/type/ObjectMapperFactoryTest.java
Fixed issue #116 
devon4j/modules/json/src/test/java/com/devonfw/module/json/common/base/type/PageableJsonTest.java
has been renamed to com.devonfw.module.json.common.base.type.ObjectMapperFactoryTest
please see commit https://github.com/devonfw/devon4j/commit/2818f5d89285493d571b3df35c7b35e0152d4305
=> fixed issue #116

.travis.yml
When you are inside a travis process, you are automatically situated under the cloned repository
=> remove unnecesary clone

modules/jpa-spring-data/src/main/java/com/devonfw/module/jpa/dataaccess/api/data/GenericRepository.java
Currently our `GenericRepository` throws an `IllegalStateException` when invoking `find(ID id)` for a not existing id.
Spring Data converts this to an `InvalidDataAccessApiUsageException` this exception is missleading in my opinion.
Spring Data offers an `EmptyResultDataAccessException` which is more specific and allows easy handling e.g. in a RestService:
```java
@Override
public PersonEto getPerson(long id) {
try {
return this.ucManagePerson.findPerson(id);
} catch (EmptyResultDataAccessException e) {
throw new NotFoundException();
}
}
```
If the proposed change here is accepted, we could even implement this in `com.devonfw.module.rest.service.impl.RestServiceExceptionFacade`.
What do you think?
=> Use more specific exception for not found entity

modules/logging/pom.xml, modules/logging/src/main/java/com/devonfw/module/logging/common/impl/PerformanceLogFilter.java
I changed our `PerformanceLogFilter` to show how https://github.com/devonfw/devon4j/issues/39 can be solved.
Currently the information is logged twice, once in the original form separated by ; and now additionally in separate fields. I kept the original format for backwards compatibility. If this is not required it is changed quite easily.
The new implementation will created logs like this:
```javascript
{"timestamp":"2020-02-10T14:36:54.299+00:00","message":"http://localhost:8081/services/rest/binary/v1/binaryobject/;21;200;;","logger_name":"com.devonfw.module.logging.common.impl.PerformanceLogFilter","thread_name":"http-nio-8081-exec-7","level":"INFO","url":"http://localhost:8081/services/rest/binary/v1/binaryobject/","duration":21,"statuscode":200,"errorClass":"","errorMessage":"","appn …
```
=> Include performance info in separate fields

documentation/guide-batch-layer.asciidoc, modules/batch/src/main/java/com/devonfw/module/batch/common/base/SpringBootBatchCommandLine.java, modules/batch/src/main/java/com/devonfw/module/batch/common/impl/JobLauncherWithAdditionalRestartCapabilities.java
Rework how jobs are loaded from context (see https://github.com/devonfw/devon4j/issues/190). Made it more similar to SpringsCommandLineJobRunner, which also loads jobs by bean name.
Also the injection of required spring batch-beans as been aligned with
CommandLineJobRunner.
=> Rework of devon4j-batch module

documentation/guide-monitoring.asciidoc
=> Wrote monitoring guide

documentation/devon4j.asciidoc
When trying to add the new kafka guide to the devon4j.asciidoc I noticed that several other guides are missing. I added all missing guides in this PR.
=> Add unreferenced guides

boms/bom/pom.xml, pom.xml
spring boot 2.3.6 -> 2.3.7 (introduces e.g. kafka 2.3.7 ->2.3.8)
spring cloud greenwich RELEASE -> SR6 (avoids manual brave upgrade)
this should also address https://github.com/devonfw/devon4j/issues/272
=> Upgrad libs

modules/http-client/src/main/java/com/devonfw/module/httpclient/common/impl/AbstractAsyncServiceHttpClient.java, modules/http-client/src/main/java/com/devonfw/module/httpclient/common/impl/ErrorHandlerThrowImmediately.java, modules/service/src/main/java/com/devonfw/module/service/common/api/client/AsyncServiceClient.java, modules/service/src/main/java/com/devonfw/module/service/common/api/client/ServiceClientFactory.java, modules/service/src/main/java/com/devonfw/module/service/common/base/client/async/AbstractAsyncServiceClient.java, starters/starter-http-client-rest-async/src/test/java/com/devonfw/module/httpclient/common/impl/client/rest/HttpRestClientTest.java, starters/starter-http-client-rest-async/src/test/java/com/devonfw/module/httpclient/common/impl/client/rest/TestResultHandler.java
* Fixed bug #327 - throw exception from CompletableFuture
* extends JUnits to cover bug #324
=> #327: fix error handling for completable future

templates/server/src/main/resources/archetype-resources/.mvn/maven.config, templates/server/src/main/resources/archetype-resources/__batch__/pom.xml, templates/server/src/main/resources/archetype-resources/__earProjectName__/pom.xml, templates/server/src/main/resources/archetype-resources/api/pom.xml, templates/server/src/main/resources/archetype-resources/core/pom.xml, templates/server/src/main/resources/archetype-resources/pom.xml, templates/server/src/main/resources/archetype-resources/server/pom.xml
Completed #85 with nice-to-have-improvements
* use revision variable directly (remove `app.version` variable)
* also removed macro whitespaces to avoid broken indentation in resulting pom
=> #85: use revision variable directly

templates/server/src/main/resources/archetype-resources/core/src/test/java/__packageInPathFormat__/general/common/base/test/ApplicationComponentTest.java, templates/server/src/main/resources/archetype-resources/core/src/test/java/__packageInPathFormat__/general/common/base/test/ApplicationSubsystemTest.java
implementation part of #393 that makes the `Application*Test` classes from our archetype indirectly derive from `DbTest` to avoid issues with `JpaHelper`.
=> #393: derive Application test classes from DbTest

CHANGELOG.asciidoc, pom.xml, templates/server/src/main/resources/archetype-resources/pom.xml
Implements #216:
* now servicedocgen 1.0.0 is used
* service documentation is generated by default in regular build
* SwaggerUI is also included (requires content to be served via HTTP server)
=> #216: servicedoc 1.0.0, generate by default

documentation/Spring-native-vs-Quarkus.asciidoc, documentation/decision-between-Spring-and-Quarkus.asciidoc, documentation/devon4j.asciidoc
* Moved Spring Native vs Quarkus guide to a different place in the outline (was not shown in the outline at all before)
* Linked decision guide between Spring and Quarkus in the general Java section
=> Correction of Spring vs Quarkus guides

boms/bom/pom.xml, modules/pom.xml, pom.xml
addresses #585 with:
* kick out kafka module (no more releases of devon4j-kafka, please use spring kafka module instead)
* remove spring-cloud from our dependency-management and BOM
* update spring-boot to 2.7.7
* update jackson to 2.14.1
=> #585: get rid of spring-cloud, disable kafka module, updates 
